name: Build
on:
  push:
    paths-ignore:
    - "native/**"
    - ".github/workflows/native.yml"
  pull_request:
    paths-ignore:
    - "native/**"
    - ".github/workflows/native.yml"

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ matrix.rid }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-x86
          - os: macos-latest
            rid: osx-x64
          - os: macos-latest
            rid: osx-arm64
            skipTest: true
          - os: macos-latest
            rid: ios-arm64
            targetOS: iOS
            skipTest: true
          - os: ubuntu-latest
            rid: linux-x64
          - os: ubuntu-latest
            rid: android-arm64-v8a
            targetOS: Android
            skipTest: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: |
          cd src/PinMame.Tests
          if [[ "${{ matrix.targetOS }}" ]]; then
            dotnet build -c Release -r ${{ matrix.rid }} /p:TargetOS=${{ matrix.targetOS }}
          else
            dotnet build -c Release -r ${{ matrix.rid }}
          fi
      - name: Test
        if: matrix.skipTest != true
        run: |
          mkdir -p ~/.pinmame/roms
          curl -sl https://www.ipdb.org/files/4032/mm_109c.zip -o ~/.pinmame/roms/mm_109c.zip
          cd src/PinMame.Tests
          dotnet test -r ${{ matrix.rid }}

  dispatch:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.repository == 'vpinball/pinmame-dotnet' && github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          event-type: build-complete
